services:
  - type: web
    name: meed-recruitment
    env: python
    plan: free  # Adjust based on your Render plan
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        value: your-secret-key  # Generate a secure key (e.g., python -c "import os; print(os.urandom(24).hex())")
      - key: QUIKR_SESSION_COOKIE
        value: your_quikr_session_cookie  # Replace with actual Quikr cookie or leave as placeholder